#pragma once
THDRAW_INNEROUTLINE_BEGIN
CString INNER_TOPLINE();
CString INNER_LEFTLINE();
CString INNER_RIGHTLINE();
CString INNER_LEFTSIDELINE();
CString INNER_RIGHTSIDELINE();
CString INNER_LEFTJOINLINE();
CString INNER_RIGHTJOINLINE();
CString INNER_BOTLINE();
THDRAW_INNEROUTLINE_END
